apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coresample-deployment
spec:
  replicas: 3  
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: mywebapi
    spec:
      containers:
      - name: coresample
        image: coresample.azurecr.io/coresample        
        ports:
        - containerPort: 80
        imagePullPolicy: Always   
